### ISSUE TITLE
Ratelimiter malfunctioning

### ISSUE THREAD

**Issue by ImNimboss** [pgjones/quart-rate-limiter#1]
Hello! The ratelimiter doesn't work according to it's designated time period and *always* ratelimits me, no matter what.

Here's my code:
```python
from quart import Quart, jsonify, request
from requests import get
from quart_rate_limiter import RateLimiter, rate_limit, RateLimit
from quart_cors import cors
from datetime import timedelta
from json import loads

app = Quart(__name__)
app = cors(app, allow_origin = 'URL')
ratelimiter = RateLimiter(app, default_limits = [RateLimit(1, timedelta(seconds = 2))])

@app.route('/my-route', methods = ['POST'])
# @rate_limit(1, timedelta(seconds = 2))
async def aiapi():
    ... # irrelevant

app.run(host = '127.0.0.1', port = 5000, debug = True)
```

Why does `/my-route` *always* get ratelimited? Am I doing something wrong here? Thanks in advance.

**Comment by pgjones** [comment]
This works as I would expect - I can make 1 request in any 2 second period with all others being rate limited.

Did you mean to have the `default_limits`?

**Comment by ImNimboss** [comment]
I did mean to have `default_limits`, and it does seem to work as expected when I run the bare example. It must be a problem with the code I'm using to request to the route. Sorry!
