### ISSUE TITLE
how the counting process actually works?

### ISSUE THREAD

**Issue by rafaelcapucho** [pgjones/quart-rate-limiter#10]
Hi @pgjones ,
First thank you for all your effort to maintain a impressive amount of source projects/initiatives in the same time, I'm basically using your whole suite (Quart, Schema, Redis, Cors, Limiter) hehehe

I was configuring the limiter, it looks to work well when I test with small values, like the following:

```
@app.route('/ip')
@rate_limit(2, timedelta(seconds=5))
async def ip() -> str:
    return request.remote_addr
```

but I applied the limiter to some of my views, and I start to get a considerable amount of Denies from the clients using the API, so I started to increase its amount, currently I'm having my defined as `@rate_limit(21000, timedelta(seconds=20)` and I'm still getting too much denies to be true, I think that for real I shouldn't having being receiving not even 2% of it. 

I just moved it to the Redis Store to be able to debug it a bit to understand where the problem might live, but I'm not really understand it how it counts.

I understand that the Redis' keys are formed by the function name + the maximum number of requests + period in seconds + IP:

I have 3 rules:

1. 5000 reqs each 5 seconds (global)
2. 5000 reqs each 60 seconds (global)
3. 21000 reqs each 20 seconds (local decorator)

![image](https://github.com/pgjones/quart-rate-limiter/assets/163367/4d1e36a0-37af-4c54-92e7-6e87c0fc18d9)

**My question is**: how does it counts? because [looks like that it simply stores a timestamp as value](https://github.com/pgjones/quart-rate-limiter/blob/e7cc610a068ebcfa1c10f6b3f74ce633ecd0c3d3/src/quart_rate_limiter/redis_store.py#L33), I didn't figured out how you managed to count the amount of requests within a period. Thank you!

**Comment by pgjones** [comment]
I wrote this up some time ago [here](https://medium.com/smarkets/implementing-gcra-in-python-5df1f11aaa96) it uses the GCRA algorithm

**Comment by Danferno** [comment]
@rafaelcapucho did this ever work properly for you? I'm getting rate limited when I shouldn't be and not getting rate limited when I should be, so it feels like there's a bug somewhere.

`DEFAULT_RATE_LIMIT = {'limits': [RateLimit(1, timedelta(seconds=1)), RateLimit(3, timedelta(minutes=1))]}`
`@rate_limit(**deps.DEFAULT_RATE_LIMIT)`

I hit this endpoint 5 times within a few seconds without getting rate limited and then a few minutes later I hit this endpoint with minutes in between and I get the 1/s rate limit each time

**Comment by grggnzlz** [comment]
I replaced an existing function with the one below and observe better behavior. This also prevents the function attribute lists from growing indefinitely:
```
def _get_limits_for_view_function(
        self, view_func: Callable, blueprint: Optional[Blueprint]
    ) -> List[RateLimit]:
        if getattr(view_func, QUART_RATE_LIMITER_EXEMPT_ATTRIBUTE, False):
            return []
        else:
            rate_limits: List[RateLimit] = getattr(
                view_func, QUART_RATE_LIMITER_LIMITS_ATTRIBUTE, []
            )
            blueprint_rate_limits: List[RateLimit] = getattr(
                blueprint, QUART_RATE_LIMITER_LIMITS_ATTRIBUTE, []
            )
            return rate_limits + blueprint_rate_limits + self._default_rate_limits
```

**Comment by pgjones** [comment]
Thanks @grggnzlz, see https://github.com/pgjones/quart-rate-limiter/commit/531bd1e0f3702d19d0807076d91f024c8b02b23b

**Comment by pgjones** [comment]
Hopefully 0.11.0 does fix this, please let me know if it doesn't.
